name: Publish to npm

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install workspace deps
        run: npm ci --workspaces

      - name: Publish @trysiren/agent-toolkit
        run: npm publish --workspace ./typescript --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @trysiren/mcp
        run: npm publish --workspace ./mcp-server --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}