name: Publish MCP

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm
          cache-dependency-path: mcp-server/package-lock.json

      - name: Install deps
        run: npm ci --prefix mcp-server

      - name: Publish @trysiren/mcp
        run: cd mcp-server && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
